### ISSUE TITLE
check_credentials() does not check credentials

### ISSUE THREAD

**Issue by Mark90** [NSO-developer/ldap-auth#4]
Hello,

Commit https://github.com/NSO-developer/ldap-auth/commit/6a154665304c8db0d2b539b218cfd02de8a8b540 changed `def check_credentials(username, password):` to `def check_credentials(lc, user, user_password):`. 

Before that commit, the user's password was used to perform an LDAP Bind, thereby validating the user's credentials.

After that commit, the admin's password is used to perform an LDAP Bind. But the user's credentials are not validated anymore.

Is this intentional?

Kind regards,
Mark

**Comment by hniska** [comment]
This was just fixed,
